apiVersion: v1
kind: Service
metadata:
  name: review-v2
  namespace: dev-review
  labels:
    app: review
    version: "2.2"
spec:
  type: ClusterIP
  ports:
  - port: 8091
    targetPort: 8091
    name: http
  selector:
    app: review
    version: "2.2"
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-v2
  namespace: dev-review
  labels:
    app: review
    version: "2.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
      version: "2.2"
  template:
    metadata:
      labels:
        app: review
        version: "2.2"
    spec:
      containers:
      - name: review-v2
        image: hchetoui/review:2.2
        ports:
        - containerPort: 8091
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: host
        - name: MYSQL_NAME
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password