apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: dev-shipping
  labels:
    app: shipping
spec:
  #type: NodePort
  #type: LoadBalancer
  type: ClusterIP
  ports:
  - port: 8093
    targetPort: 8093
    name: http
  selector:
    app: shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: dev-shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: hchetoui/shipping:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8093
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: conf
              key: mysql-host
        - name: MYSQL_NAME
          valueFrom:
            configMapKeyRef:
              name: conf
              key: mysql-db-name
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: conf
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: conf
              key: rabbitmq-port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: shipping-secret
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shipping-secret
              key: rabbitmq-password

        - name: RABBITMQ_EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: conf
              key: rabbitmq-exchange-name
        - name: RABBITMQ_ROUTING_KEY
          valueFrom:
            configMapKeyRef:
              name: conf
              key: rabbitmq-routing-key