apiVersion: v1
kind: Secret
metadata:
  name: notif-secret
  namespace: dev-notification
type: Opaque
data:
  gmail-sender-user: ZWNvbW1lcmNlbWljcm9zZXJ2aWNlQGdtYWlsLmNvbQ== # Add a gmail to send notification. change <mail> by you gmail
  gmail-sender-password: RWMwbW1lcmNlQA== # Add password for the gmail, change <password> by your gmail password
  rabbitmq-username: YWRtaW4= # admin, Change the username by your brokers username
  rabbitmq-password: YWRtaW4= # Change the password by your brokers password
