order:
  url: http://localhost:8090

payment:
  url: http://localhost:92

cart:
  url: http://localhost:8092

shipping:
  url: http://localhost:8093

server:
  port: 8094

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  exchange: sqli-exchange
  routing_key: sqli.key
  queue: sqli.#
