apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-hosts-conf
  namespace: dev-checkout
data:
  rabbitmq_host: mu-rabbit-rabbitmq.dev-rabbitmq-broker.svc.cluster.local
  rabbitmq_port: "5672"
  cart_host: http://cart.dev-cart.svc.cluster.local:8092
  order_host: http://order.dev-order.svc.cluster.local:8095
  payment_host: http://payment.dev-payment.svc.cluster.local:8092
  shipping_host: http://shipping.dev-shipping.svc.cluster.local:8093